package com.pc.cf.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("authentication", "id", Authentication.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("city", "id", City.class);
		arp.addMapping("codes", "id", Codes.class);
		arp.addMapping("company", "id", Company.class);
		arp.addMapping("crowd", "id", Crowd.class);
		arp.addMapping("crowditem", "id", Crowditem.class);
		arp.addMapping("demand", "id", Demand.class);
		arp.addMapping("demandtype", "id", Demandtype.class);
		arp.addMapping("enclosure", "id", Enclosure.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("inquiry", "id", Inquiry.class);
		arp.addMapping("inquiryprice", "id", Inquiryprice.class);
		arp.addMapping("keyword", "id", Keyword.class);
		arp.addMapping("quotedprice", "id", Quotedprice.class);
		arp.addMapping("server", "id", Server.class);
		arp.addMapping("tb_tfw_blog", "f_it_id", TbTfwBlog.class);
		arp.addMapping("tb_tfw_tzgg", "F_IT_XL", TbTfwTzgg.class);
		arp.addMapping("tfw_attach", "ID", TfwAttach.class);
		arp.addMapping("tfw_dept", "ID", TfwDept.class);
		arp.addMapping("tfw_dict", "ID", TfwDict.class);
		arp.addMapping("tfw_generate", "ID", TfwGenerate.class);
		arp.addMapping("tfw_login_log", "ID", TfwLoginLog.class);
		arp.addMapping("tfw_menu", "ID", TfwMenu.class);
		arp.addMapping("tfw_operation_log", "ID", TfwOperationLog.class);
		arp.addMapping("tfw_parameter", "ID", TfwParameter.class);
		arp.addMapping("tfw_relation", "ID", TfwRelation.class);
		arp.addMapping("tfw_role", "ID", TfwRole.class);
		arp.addMapping("tfw_role_ext", "ID", TfwRoleExt.class);
		arp.addMapping("tfw_user", "ID", TfwUser.class);
		arp.addMapping("userinfo", "id", Userinfo.class);
	}
}

