package com.pc.cf.model;

import com.pc.cf.model.base.BaseAuthentication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authentication extends BaseAuthentication<Authentication> {
	
}
