package com.pc.cf.model;

import com.pc.cf.model.base.BaseInquiryprice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inquiryprice extends BaseInquiryprice<Inquiryprice> {
	
}
