package com.pc.cf.model;

import com.pc.cf.model.base.BaseQuotedprice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Quotedprice extends BaseQuotedprice<Quotedprice> {
	
}
