package com.pc.cf.model;

import com.pc.cf.model.base.BaseTfwGenerate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TfwGenerate extends BaseTfwGenerate<TfwGenerate> {
	
}
