package com.pc.cf.model;

import com.pc.cf.model.base.BaseTfwLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TfwLoginLog extends BaseTfwLoginLog<TfwLoginLog> {
	
}
