package com.pc.cf.model;

import com.pc.cf.model.base.BaseTfwOperationLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TfwOperationLog extends BaseTfwOperationLog<TfwOperationLog> {
	
}
