package com.pc.cf.model;

import com.pc.cf.model.base.BaseTfwParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TfwParameter extends BaseTfwParameter<TfwParameter> {
	
}
