package com.pc.cf.model;

import com.pc.cf.model.base.BaseTfwRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TfwRelation extends BaseTfwRelation<TfwRelation> {
	
}
