package ikkong.platform.controller;

import java.util.Map;
import ikkong.core.base.BaseController;
import ikkong.core.jfinal.ext.kit.JsonKit;
import ikkong.system.controller.base.UrlPermissController;
import ikkong.platform.model.Authentication;
import ikkong.platform.service.AuthenticationService;
import ikkong.platform.service.impl.AuthenticationServiceImpl;

/**
 * Generated by Blade.
 * 2017-11-30 14:24:47
 */
public class AuthenticationController extends UrlPermissController {
	private static String CODE = "authentication";
	private static String PERFIX = "authentication";
	private static String LIST_SOURCE = "Authentication.list";
	private static String BASE_PATH = "/platform/authentication/";
	
	AuthenticationService service = new AuthenticationServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "authentication.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "authentication_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Authentication authentication = service.findById(id);
		setAttr("model", JsonKit.toJson(authentication));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "authentication_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Authentication authentication = service.findById(id);
		setAttr("model", JsonKit.toJson(authentication));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "authentication_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Authentication authentication = mapping(PERFIX, Authentication.class);
		boolean temp = service.save(authentication);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Authentication authentication = mapping(PERFIX, Authentication.class);
		authentication.setVersion(authentication.getVersion()+1);
		boolean temp = service.update(authentication);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
