package ikkong.platform.controller;

import java.util.Map;
import ikkong.core.base.BaseController;
import ikkong.core.jfinal.ext.kit.JsonKit;
import ikkong.system.controller.base.UrlPermissController;
import ikkong.platform.model.Crowditem;
import ikkong.platform.service.CrowditemService;
import ikkong.platform.service.impl.CrowditemServiceImpl;

/**
 * Generated by Blade.
 * 2018-01-28 15:39:09
 */
public class CrowditemController extends UrlPermissController {
	private static String CODE = "crowditem";
	private static String PERFIX = "crowditem";
	private static String LIST_SOURCE = "Crowditem.list";
	private static String BASE_PATH = "/platform/crowditem/";
	
	CrowditemService service = new CrowditemServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "crowditem.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "crowditem_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Crowditem crowditem = service.findById(id);
		setAttr("model", JsonKit.toJson(crowditem));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "crowditem_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Crowditem crowditem = service.findById(id);
		setAttr("model", JsonKit.toJson(crowditem));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "crowditem_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Crowditem crowditem = mapping(PERFIX, Crowditem.class);
		boolean temp = service.save(crowditem);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Crowditem crowditem = mapping(PERFIX, Crowditem.class);
		crowditem.setVersion(crowditem.getVersion()+1);
		boolean temp = service.update(crowditem);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
