package ikkong.platform.controller;

import java.util.Map;
import ikkong.core.base.BaseController;
import ikkong.core.jfinal.ext.kit.JsonKit;
import ikkong.system.controller.base.UrlPermissController;
import ikkong.platform.model.Demandtype;
import ikkong.platform.service.DemandtypeService;

/**
 * Generated by Blade.
 * 2017-12-05 01:01:32
 */
public class DemandtypeController extends UrlPermissController {
	private static String CODE = "demandtype";
	private static String PERFIX = "demandtype";
	private static String LIST_SOURCE = "Demandtype.list";
	private static String BASE_PATH = "/platform/demandtype/";
	
	DemandtypeService service = new DemandtypeServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "demandtype.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "demandtype_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Demandtype demandtype = service.findById(id);
		setAttr("model", JsonKit.toJson(demandtype));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "demandtype_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Demandtype demandtype = service.findById(id);
		setAttr("model", JsonKit.toJson(demandtype));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "demandtype_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Demandtype demandtype = mapping(PERFIX, Demandtype.class);
		boolean temp = service.save(demandtype);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Demandtype demandtype = mapping(PERFIX, Demandtype.class);
		demandtype.setVersion(demandtype.getVersion()+1);
		boolean temp = service.update(demandtype);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
