package ikkong.platform.controller;

import java.util.Map;
import ikkong.core.base.BaseController;
import ikkong.core.jfinal.ext.kit.JsonKit;
import ikkong.system.controller.base.UrlPermissController;
import ikkong.platform.model.Goods;
import ikkong.platform.service.GoodsService;
import ikkong.platform.service.impl.GoodsServiceImpl;

/**
 * Generated by Blade.
 * 2017-12-05 00:31:02
 */
public class GoodsController extends UrlPermissController {
	private static String CODE = "goods";
	private static String PERFIX = "goods";
	private static String LIST_SOURCE = "Goods.list";
	private static String BASE_PATH = "/platform/goods/";
	
	GoodsService service = new GoodsServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "goods.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "goods_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Goods goods = service.findById(id);
		setAttr("model", JsonKit.toJson(goods));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "goods_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Goods goods = service.findById(id);
		setAttr("model", JsonKit.toJson(goods));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "goods_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Goods goods = mapping(PERFIX, Goods.class);
		boolean temp = service.save(goods);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Goods goods = mapping(PERFIX, Goods.class);
		goods.setVersion(goods.getVersion()+1);
		boolean temp = service.update(goods);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
