package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Crowditem;
import ikkong.platform.service.CrowditemService;

/**
 * Generated by Blade.
 * 2018-01-28 15:39:09
 */
public class CrowditemServiceImpl extends BaseService<Crowditem> implements CrowditemService{

}
