package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Demandtype;
import ikkong.platform.service.DemandtypeService;

/**
 * Generated by Blade.
 * 2017-12-05 01:01:32
 */
public class DemandtypeServiceImpl extends BaseService<Demandtype> implements DemandtypeService{

}
