package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Goods;
import ikkong.platform.service.GoodsService;

/**
 * Generated by Blade.
 * 2017-12-05 00:31:02
 */
public class GoodsServiceImpl extends BaseService<Goods> implements GoodsService{

}
