package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Server;
import ikkong.platform.service.ServerService;

/**
 * Generated by Blade.
 * 2017-11-28 16:15:48
 */
public class ServerServiceImpl extends BaseService<Server> implements ServerService{

}
