package ikkong.platform.model;

import ikkong.core.annotation.BindID;
import ikkong.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

/**
 * Generated by Blade.
 * 2017-11-30 14:24:47
 */
@Table(name = "authentication")
@BindID(name = "ID")
@SuppressWarnings("serial")
public class Authentication extends BaseModel {
    private Integer id;
    private Integer companyId;
    private Integer creatTime;
    private Integer isThree; //是否三证合一
    private Integer status;
    private String businessNumber; //工商注册号
    private String cardPhoto; //身份证
    private String contacts; //联系人
    private String creditCode; //企业信用代码
    private String name; //企业全称
    private String organizationCard; //组织机构代码证
    private String organizationCode; //组织机构代码
    private String phone; //电话号码
    private String photo; //营业执照
    private String representative; //法人姓名
    private String representativeCard; //法人身份证
    private String representativePhone; //法人手机号
    private String taxCard; //税务登记证
    private String taxpayersAlias; //纳税人识别号

    @AutoID
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(Integer creatTime) {
        this.creatTime = creatTime;
    }

    public Integer getIsThree() {
        return isThree;
    }

    public void setIsThree(Integer isThree) {
        this.isThree = isThree;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getBusinessNumber() {
        return businessNumber;
    }

    public void setBusinessNumber(String businessNumber) {
        this.businessNumber = businessNumber;
    }

    public String getCardPhoto() {
        return cardPhoto;
    }

    public void setCardPhoto(String cardPhoto) {
        this.cardPhoto = cardPhoto;
    }

    public String getContacts() {
        return contacts;
    }

    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    public String getCreditCode() {
        return creditCode;
    }

    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrganizationCard() {
        return organizationCard;
    }

    public void setOrganizationCard(String organizationCard) {
        this.organizationCard = organizationCard;
    }

    public String getOrganizationCode() {
        return organizationCode;
    }

    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getRepresentative() {
        return representative;
    }

    public void setRepresentative(String representative) {
        this.representative = representative;
    }

    public String getRepresentativeCard() {
        return representativeCard;
    }

    public void setRepresentativeCard(String representativeCard) {
        this.representativeCard = representativeCard;
    }

    public String getRepresentativePhone() {
        return representativePhone;
    }

    public void setRepresentativePhone(String representativePhone) {
        this.representativePhone = representativePhone;
    }

    public String getTaxCard() {
        return taxCard;
    }

    public void setTaxCard(String taxCard) {
        this.taxCard = taxCard;
    }

    public String getTaxpayersAlias() {
        return taxpayersAlias;
    }

    public void setTaxpayersAlias(String taxpayersAlias) {
        this.taxpayersAlias = taxpayersAlias;
    }

}
