package ikkong.platform.model;

import ikkong.core.annotation.BindID;
import ikkong.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

/**
 * Generated by Blade.
 * 2017-11-28 16:15:48
 */
@Table(name = "server")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Server extends BaseModel {
    	private Integer id;
    	private Integer companyid;
    	private Integer creatdate;
    	private Integer demandtype1; //需求一级类型
    	private Integer demandtype2; //需求二级类型
    	private Integer prices; //询价结束日期
    	private Integer type; //草稿 还是预览
    	private String address;
    	private String cities;
    	private String contacts;
    	private String counties;
    	private String description; //详细描述
    	private String phone;
    	private String photo; //需求图片附件
    	private String provincial;
    	private String title; //询价主题
    	private String unit; //规格

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getCompanyid() {
    		return companyid;
    	}

    	public void setCompanyid(Integer companyid) {
    		this.companyid = companyid;
    	}

    	public Integer getCreatdate() {
    		return creatdate;
    	}

    	public void setCreatdate(Integer creatdate) {
    		this.creatdate = creatdate;
    	}

    	public Integer getDemandtype1() {
    		return demandtype1;
    	}

    	public void setDemandtype1(Integer demandtype1) {
    		this.demandtype1 = demandtype1;
    	}

    	public Integer getDemandtype2() {
    		return demandtype2;
    	}

    	public void setDemandtype2(Integer demandtype2) {
    		this.demandtype2 = demandtype2;
    	}

    	public Integer getPrices() {
    		return prices;
    	}

    	public void setPrices(Integer prices) {
    		this.prices = prices;
    	}

    	public Integer getType() {
    		return type;
    	}

    	public void setType(Integer type) {
    		this.type = type;
    	}

    	public String getAddress() {
    		return address;
    	}

    	public void setAddress(String address) {
    		this.address = address;
    	}

    	public String getCities() {
    		return cities;
    	}

    	public void setCities(String cities) {
    		this.cities = cities;
    	}

    	public String getContacts() {
    		return contacts;
    	}

    	public void setContacts(String contacts) {
    		this.contacts = contacts;
    	}

    	public String getCounties() {
    		return counties;
    	}

    	public void setCounties(String counties) {
    		this.counties = counties;
    	}

    	public String getDescription() {
    		return description;
    	}

    	public void setDescription(String description) {
    		this.description = description;
    	}

    	public String getPhone() {
    		return phone;
    	}

    	public void setPhone(String phone) {
    		this.phone = phone;
    	}

    	public String getPhoto() {
    		return photo;
    	}

    	public void setPhoto(String photo) {
    		this.photo = photo;
    	}

    	public String getProvincial() {
    		return provincial;
    	}

    	public void setProvincial(String provincial) {
    		this.provincial = provincial;
    	}

    	public String getTitle() {
    		return title;
    	}

    	public void setTitle(String title) {
    		this.title = title;
    	}

    	public String getUnit() {
    		return unit;
    	}

    	public void setUnit(String unit) {
    		this.unit = unit;
    	}

}
