package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Authentication;
import ikkong.platform.service.AuthenticationService;

/**
 * Generated by Blade.
 * 2017-11-30 14:24:47
 */
public class AuthenticationServiceImpl extends BaseService<Authentication> implements AuthenticationService{

}
