package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Blog;
import ikkong.platform.service.BlogService;

/**
 * Generated by Blade.
 * 2017-12-28 17:46:55
 */
public class BlogServiceImpl extends BaseService<Blog> implements BlogService{

}
