package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.City;
import ikkong.platform.service.CityService;

/**
 * Generated by Blade.
 * 2017-11-28 14:39:25
 */
public class CityServiceImpl extends BaseService<City> implements CityService {

}
