package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Company;
import ikkong.platform.service.CompanyService;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class CompanyServiceImpl extends BaseService<Company> implements CompanyService {

}
