package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Crowd;
import ikkong.platform.service.CrowdService;

/**
 * Generated by Blade.
 * 2018-01-28 15:39:09
 */
public class CrowdServiceImpl extends BaseService<Crowd> implements CrowdService{

}
