package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Demandtype;
import ikkong.platform.service.DemandtypeService;

/**
 * Generated by Blade.
 * 2017-11-28 14:39:25
 */
public class DemandTypeServiceImpl extends BaseService<Demandtype> implements DemandtypeService {

}
