package ikkong.platform.service.impl;

import ikkong.core.base.service.impl.BaseService;
import ikkong.platform.model.Demand;
import ikkong.platform.service.DemandService;

/**
 * Generated by Blade.
 * 2017-11-28 14:39:25
 */
public class DemandServiceImpl extends BaseService<Demand> implements DemandService{

}
