package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Crowd;

/**
 * Generated by Blade.
 * 2018-01-28 15:39:09
 */
public interface CrowdService extends IService<Crowd>{

}
