package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Goods;

/**
 * Generated by Blade.
 * 2017-12-05 00:31:02
 */
public interface GoodsService extends IService<Goods>{

}
