package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Server;

/**
 * Generated by Blade.
 * 2017-11-28 16:15:48
 */
public interface ServerService extends IService<Server>{

}
