package ikkong.platform.controller;

import ikkong.core.jfinal.ext.kit.JsonKit;
import ikkong.platform.meta.intercept.DemandIntercept;
import ikkong.platform.model.Demand;
import ikkong.platform.service.DemandService;
import ikkong.platform.service.impl.DemandServiceImpl;
import ikkong.system.controller.base.UrlPermissController;

/**
 * Generated by Blade.
 * 2017-11-28 14:39:25
 */
public class DemandController extends UrlPermissController {
	private static String CODE = "demand";
	private static String PERFIX = "demand";
	private static String LIST_SOURCE = "Demand.list";
	private static String BASE_PATH = "/platform/demand/";
	
	DemandService service = new DemandServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "demand.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "demand_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Demand demand = service.findById(id);
		setAttr("model", JsonKit.toJson(demand));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "demand_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Demand demand = service.findById(id);
		setAttr("model", JsonKit.toJson(demand));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "demand_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE, new DemandIntercept());
		renderJson(grid);
	}

	public void save() {
		Demand demand = mapping(PERFIX, Demand.class);
		boolean temp = service.save(demand);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Demand demand = mapping(PERFIX, Demand.class);
		boolean temp = service.update(demand);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
