package ikkong.platform.controller;

import ikkong.core.jfinal.ext.kit.JsonKit;
import ikkong.platform.model.Server;
import ikkong.platform.service.ServerService;
import ikkong.platform.service.impl.ServerServiceImpl;
import ikkong.system.controller.base.UrlPermissController;

/**
 * Generated by Blade.
 * 2017-11-28 16:15:48
 */
public class ServerController extends UrlPermissController {
	private static String CODE = "server";
	private static String PERFIX = "server";
	private static String LIST_SOURCE = "Server.list";
	private static String BASE_PATH = "/platform/server/";
	
	ServerService service = new ServerServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "server.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "server_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Server server = service.findById(id);
		setAttr("model", JsonKit.toJson(server));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "server_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Server server = service.findById(id);
		setAttr("model", JsonKit.toJson(server));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "server_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Server server = mapping(PERFIX, Server.class);
		boolean temp = service.save(server);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Server server = mapping(PERFIX, Server.class);
		boolean temp = service.update(server);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
