package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwRelation<M extends BaseTfwRelation<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setMENUID(java.lang.Integer MENUID) {
		set("MENUID", MENUID);
		return (M)this;
	}
	
	public java.lang.Integer getMENUID() {
		return getInt("MENUID");
	}

	public M setROLEID(java.lang.Integer ROLEID) {
		set("ROLEID", ROLEID);
		return (M)this;
	}
	
	public java.lang.Integer getROLEID() {
		return getInt("ROLEID");
	}

}
