package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setNumber(java.lang.String number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.String getNumber() {
		return getStr("number");
	}

	public M setContacts(java.lang.String contacts) {
		set("contacts", contacts);
		return (M)this;
	}
	
	public java.lang.String getContacts() {
		return getStr("contacts");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}
	
	public java.lang.String getQq() {
		return getStr("qq");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setWeb(java.lang.String web) {
		set("web", web);
		return (M)this;
	}
	
	public java.lang.String getWeb() {
		return getStr("web");
	}

	public M setBusiness(java.lang.Integer business) {
		set("business", business);
		return (M)this;
	}
	
	public java.lang.Integer getBusiness() {
		return getInt("business");
	}

	public M setOperation(java.lang.Integer operation) {
		set("operation", operation);
		return (M)this;
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (M)this;
	}
	
	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public M setScale(java.lang.Integer scale) {
		set("scale", scale);
		return (M)this;
	}
	
	public java.lang.Integer getScale() {
		return getInt("scale");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}
	
	public java.lang.String getPhoto() {
		return getStr("photo");
	}

	public M setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
		return (M)this;
	}
	
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public M setUser(java.lang.Integer user) {
		set("user", user);
		return (M)this;
	}
	
	public java.lang.Integer getUser() {
		return getInt("user");
	}

	public M setAuthentication(java.lang.Integer authentication) {
		set("authentication", authentication);
		return (M)this;
	}
	
	public java.lang.Integer getAuthentication() {
		return getInt("authentication");
	}

	public M setGoods(java.lang.String goods) {
		set("goods", goods);
		return (M)this;
	}
	
	public java.lang.String getGoods() {
		return getStr("goods");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
