package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwGenerate<M extends BaseTfwGenerate<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setREALPATH(java.lang.String REALPATH) {
		set("REALPATH", REALPATH);
		return (M)this;
	}
	
	public java.lang.String getREALPATH() {
		return getStr("REALPATH");
	}

	public M setPACKAGENAME(java.lang.String PACKAGENAME) {
		set("PACKAGENAME", PACKAGENAME);
		return (M)this;
	}
	
	public java.lang.String getPACKAGENAME() {
		return getStr("PACKAGENAME");
	}

	public M setMODELNAME(java.lang.String MODELNAME) {
		set("MODELNAME", MODELNAME);
		return (M)this;
	}
	
	public java.lang.String getMODELNAME() {
		return getStr("MODELNAME");
	}

	public M setTABLENAME(java.lang.String TABLENAME) {
		set("TABLENAME", TABLENAME);
		return (M)this;
	}
	
	public java.lang.String getTABLENAME() {
		return getStr("TABLENAME");
	}

	public M setPKNAME(java.lang.String PKNAME) {
		set("PKNAME", PKNAME);
		return (M)this;
	}
	
	public java.lang.String getPKNAME() {
		return getStr("PKNAME");
	}

	public M setTIPS(java.lang.String TIPS) {
		set("TIPS", TIPS);
		return (M)this;
	}
	
	public java.lang.String getTIPS() {
		return getStr("TIPS");
	}

}
