package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthentication<M extends BaseAuthentication<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCompanyId(java.lang.Integer companyId) {
		set("companyId", companyId);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("companyId");
	}

	public M setIsThree(java.lang.Integer isThree) {
		set("isThree", isThree);
		return (M)this;
	}
	
	public java.lang.Integer getIsThree() {
		return getInt("isThree");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCreditCode(java.lang.String creditCode) {
		set("creditCode", creditCode);
		return (M)this;
	}
	
	public java.lang.String getCreditCode() {
		return getStr("creditCode");
	}

	public M setRepresentative(java.lang.String representative) {
		set("representative", representative);
		return (M)this;
	}
	
	public java.lang.String getRepresentative() {
		return getStr("representative");
	}

	public M setRepresentativeCard(java.lang.String representativeCard) {
		set("representativeCard", representativeCard);
		return (M)this;
	}
	
	public java.lang.String getRepresentativeCard() {
		return getStr("representativeCard");
	}

	public M setRepresentativePhone(java.lang.String representativePhone) {
		set("representativePhone", representativePhone);
		return (M)this;
	}
	
	public java.lang.String getRepresentativePhone() {
		return getStr("representativePhone");
	}

	public M setContacts(java.lang.String contacts) {
		set("contacts", contacts);
		return (M)this;
	}
	
	public java.lang.String getContacts() {
		return getStr("contacts");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}
	
	public java.lang.String getPhoto() {
		return getStr("photo");
	}

	public M setCardPhoto(java.lang.String cardPhoto) {
		set("cardPhoto", cardPhoto);
		return (M)this;
	}
	
	public java.lang.String getCardPhoto() {
		return getStr("cardPhoto");
	}

	public M setCreatTime(java.lang.Integer creatTime) {
		set("creatTime", creatTime);
		return (M)this;
	}
	
	public java.lang.Integer getCreatTime() {
		return getInt("creatTime");
	}

	public M setBusinessNumber(java.lang.String businessNumber) {
		set("businessNumber", businessNumber);
		return (M)this;
	}
	
	public java.lang.String getBusinessNumber() {
		return getStr("businessNumber");
	}

	public M setOrganizationCode(java.lang.String organizationCode) {
		set("organizationCode", organizationCode);
		return (M)this;
	}
	
	public java.lang.String getOrganizationCode() {
		return getStr("organizationCode");
	}

	public M setTaxCard(java.lang.String taxCard) {
		set("taxCard", taxCard);
		return (M)this;
	}
	
	public java.lang.String getTaxCard() {
		return getStr("taxCard");
	}

	public M setOrganizationCard(java.lang.String organizationCard) {
		set("organizationCard", organizationCard);
		return (M)this;
	}
	
	public java.lang.String getOrganizationCard() {
		return getStr("organizationCard");
	}

	public M setTaxpayersAlias(java.lang.String taxpayersAlias) {
		set("taxpayersAlias", taxpayersAlias);
		return (M)this;
	}
	
	public java.lang.String getTaxpayersAlias() {
		return getStr("taxpayersAlias");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
