package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInquiry<M extends BaseInquiry<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDemandid(java.lang.Integer demandid) {
		set("demandid", demandid);
		return (M)this;
	}
	
	public java.lang.Integer getDemandid() {
		return getInt("demandid");
	}

	public M setGoodId(java.lang.Integer goodId) {
		set("goodId", goodId);
		return (M)this;
	}
	
	public java.lang.Integer getGoodId() {
		return getInt("goodId");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}

	public M setPrice(java.lang.Integer price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setCreatdate(java.lang.Integer creatdate) {
		set("creatdate", creatdate);
		return (M)this;
	}
	
	public java.lang.Integer getCreatdate() {
		return getInt("creatdate");
	}

}
