package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwOperationLog<M extends BaseTfwOperationLog<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setLOGNAME(java.lang.String LOGNAME) {
		set("LOGNAME", LOGNAME);
		return (M)this;
	}
	
	public java.lang.String getLOGNAME() {
		return getStr("LOGNAME");
	}

	public M setUSERID(java.lang.String USERID) {
		set("USERID", USERID);
		return (M)this;
	}
	
	public java.lang.String getUSERID() {
		return getStr("USERID");
	}

	public M setCLASSNAME(java.lang.String CLASSNAME) {
		set("CLASSNAME", CLASSNAME);
		return (M)this;
	}
	
	public java.lang.String getCLASSNAME() {
		return getStr("CLASSNAME");
	}

	public M setMETHOD(java.lang.String METHOD) {
		set("METHOD", METHOD);
		return (M)this;
	}
	
	public java.lang.String getMETHOD() {
		return getStr("METHOD");
	}

	public M setCREATETIME(java.util.Date CREATETIME) {
		set("CREATETIME", CREATETIME);
		return (M)this;
	}
	
	public java.util.Date getCREATETIME() {
		return get("CREATETIME");
	}

	public M setSUCCEED(java.lang.String SUCCEED) {
		set("SUCCEED", SUCCEED);
		return (M)this;
	}
	
	public java.lang.String getSUCCEED() {
		return getStr("SUCCEED");
	}

	public M setMESSAGE(java.lang.String MESSAGE) {
		set("MESSAGE", MESSAGE);
		return (M)this;
	}
	
	public java.lang.String getMESSAGE() {
		return getStr("MESSAGE");
	}

}
