package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbTfwTzgg<M extends BaseTbTfwTzgg<M>> extends Model<M> implements IBean {

	public M setFItXl(java.lang.Integer fItXl) {
		set("F_IT_XL", fItXl);
		return (M)this;
	}
	
	public java.lang.Integer getFItXl() {
		return getInt("F_IT_XL");
	}

	public M setFVcBt(java.lang.String fVcBt) {
		set("F_VC_BT", fVcBt);
		return (M)this;
	}
	
	public java.lang.String getFVcBt() {
		return getStr("F_VC_BT");
	}

	public M setFItLx(java.lang.Integer fItLx) {
		set("F_IT_LX", fItLx);
		return (M)this;
	}
	
	public java.lang.Integer getFItLx() {
		return getInt("F_IT_LX");
	}

	public M setFTxNr(java.lang.String fTxNr) {
		set("F_TX_NR", fTxNr);
		return (M)this;
	}
	
	public java.lang.String getFTxNr() {
		return getStr("F_TX_NR");
	}

	public M setFDtFbsj(java.util.Date fDtFbsj) {
		set("F_DT_FBSJ", fDtFbsj);
		return (M)this;
	}
	
	public java.util.Date getFDtFbsj() {
		return get("F_DT_FBSJ");
	}

	public M setFDtCjsj(java.util.Date fDtCjsj) {
		set("F_DT_CJSJ", fDtCjsj);
		return (M)this;
	}
	
	public java.util.Date getFDtCjsj() {
		return get("F_DT_CJSJ");
	}

	public M setFItCjr(java.lang.Integer fItCjr) {
		set("F_IT_CJR", fItCjr);
		return (M)this;
	}
	
	public java.lang.Integer getFItCjr() {
		return getInt("F_IT_CJR");
	}

	public M setFItTp(java.lang.Integer fItTp) {
		set("F_IT_TP", fItTp);
		return (M)this;
	}
	
	public java.lang.Integer getFItTp() {
		return getInt("F_IT_TP");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

}
