package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwAttach<M extends BaseTfwAttach<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setCODE(java.lang.String CODE) {
		set("CODE", CODE);
		return (M)this;
	}
	
	public java.lang.String getCODE() {
		return getStr("CODE");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setURL(java.lang.String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public java.lang.String getURL() {
		return getStr("URL");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setCREATER(java.lang.Integer CREATER) {
		set("CREATER", CREATER);
		return (M)this;
	}
	
	public java.lang.Integer getCREATER() {
		return getInt("CREATER");
	}

	public M setCREATETIME(java.util.Date CREATETIME) {
		set("CREATETIME", CREATETIME);
		return (M)this;
	}
	
	public java.util.Date getCREATETIME() {
		return get("CREATETIME");
	}

}
