package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwRole<M extends BaseTfwRole<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setNUM(java.lang.Integer NUM) {
		set("NUM", NUM);
		return (M)this;
	}
	
	public java.lang.Integer getNUM() {
		return getInt("NUM");
	}

	public M setPID(java.lang.Integer PID) {
		set("PID", PID);
		return (M)this;
	}
	
	public java.lang.Integer getPID() {
		return getInt("PID");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setDEPTID(java.lang.Integer DEPTID) {
		set("DEPTID", DEPTID);
		return (M)this;
	}
	
	public java.lang.Integer getDEPTID() {
		return getInt("DEPTID");
	}

	public M setTIPS(java.lang.String TIPS) {
		set("TIPS", TIPS);
		return (M)this;
	}
	
	public java.lang.String getTIPS() {
		return getStr("TIPS");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

}
