package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInquiryprice<M extends BaseInquiryprice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setQuotedid(java.lang.Integer quotedid) {
		set("quotedid", quotedid);
		return (M)this;
	}
	
	public java.lang.Integer getQuotedid() {
		return getInt("quotedid");
	}

	public M setInquiryid(java.lang.Integer inquiryid) {
		set("inquiryid", inquiryid);
		return (M)this;
	}
	
	public java.lang.Integer getInquiryid() {
		return getInt("inquiryid");
	}

	public M setPrice(java.lang.Integer price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public M setCreatdate(java.lang.Integer creatdate) {
		set("creatdate", creatdate);
		return (M)this;
	}
	
	public java.lang.Integer getCreatdate() {
		return getInt("creatdate");
	}

}
