package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwRoleExt<M extends BaseTfwRoleExt<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setUSERID(java.lang.String USERID) {
		set("USERID", USERID);
		return (M)this;
	}
	
	public java.lang.String getUSERID() {
		return getStr("USERID");
	}

	public M setROLEIN(java.lang.String ROLEIN) {
		set("ROLEIN", ROLEIN);
		return (M)this;
	}
	
	public java.lang.String getROLEIN() {
		return getStr("ROLEIN");
	}

	public M setROLEOUT(java.lang.String ROLEOUT) {
		set("ROLEOUT", ROLEOUT);
		return (M)this;
	}
	
	public java.lang.String getROLEOUT() {
		return getStr("ROLEOUT");
	}

}
