package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwMenu<M extends BaseTfwMenu<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setCODE(java.lang.String CODE) {
		set("CODE", CODE);
		return (M)this;
	}
	
	public java.lang.String getCODE() {
		return getStr("CODE");
	}

	public M setPCODE(java.lang.String PCODE) {
		set("PCODE", PCODE);
		return (M)this;
	}
	
	public java.lang.String getPCODE() {
		return getStr("PCODE");
	}

	public M setALIAS(java.lang.String ALIAS) {
		set("ALIAS", ALIAS);
		return (M)this;
	}
	
	public java.lang.String getALIAS() {
		return getStr("ALIAS");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setICON(java.lang.String ICON) {
		set("ICON", ICON);
		return (M)this;
	}
	
	public java.lang.String getICON() {
		return getStr("ICON");
	}

	public M setURL(java.lang.String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public java.lang.String getURL() {
		return getStr("URL");
	}

	public M setNUM(java.lang.Integer NUM) {
		set("NUM", NUM);
		return (M)this;
	}
	
	public java.lang.Integer getNUM() {
		return getInt("NUM");
	}

	public M setLEVELS(java.lang.Integer LEVELS) {
		set("LEVELS", LEVELS);
		return (M)this;
	}
	
	public java.lang.Integer getLEVELS() {
		return getInt("LEVELS");
	}

	public M setSOURCE(java.lang.String SOURCE) {
		set("SOURCE", SOURCE);
		return (M)this;
	}
	
	public java.lang.String getSOURCE() {
		return getStr("SOURCE");
	}

	public M setPATH(java.lang.String PATH) {
		set("PATH", PATH);
		return (M)this;
	}
	
	public java.lang.String getPATH() {
		return getStr("PATH");
	}

	public M setTIPS(java.lang.String TIPS) {
		set("TIPS", TIPS);
		return (M)this;
	}
	
	public java.lang.String getTIPS() {
		return getStr("TIPS");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setISOPEN(java.lang.String ISOPEN) {
		set("ISOPEN", ISOPEN);
		return (M)this;
	}
	
	public java.lang.String getISOPEN() {
		return getStr("ISOPEN");
	}

	public M setISTEMPLATE(java.lang.String ISTEMPLATE) {
		set("ISTEMPLATE", ISTEMPLATE);
		return (M)this;
	}
	
	public java.lang.String getISTEMPLATE() {
		return getStr("ISTEMPLATE");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

}
