package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuotedprice<M extends BaseQuotedprice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setDemandid(java.lang.Integer demandid) {
		set("demandid", demandid);
		return (M)this;
	}
	
	public java.lang.Integer getDemandid() {
		return getInt("demandid");
	}

	public M setCompanyid(java.lang.Integer companyid) {
		set("companyid", companyid);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyid() {
		return getInt("companyid");
	}

	public M setFreight(java.lang.Integer freight) {
		set("freight", freight);
		return (M)this;
	}
	
	public java.lang.Integer getFreight() {
		return getInt("freight");
	}

	public M setPricedescribe(java.lang.String pricedescribe) {
		set("pricedescribe", pricedescribe);
		return (M)this;
	}
	
	public java.lang.String getPricedescribe() {
		return getStr("pricedescribe");
	}

	public M setEffective(java.lang.Integer effective) {
		set("effective", effective);
		return (M)this;
	}
	
	public java.lang.Integer getEffective() {
		return getInt("effective");
	}

	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}
	
	public java.lang.String getUser() {
		return getStr("user");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setCreatdate(java.lang.Integer creatdate) {
		set("creatdate", creatdate);
		return (M)this;
	}
	
	public java.lang.Integer getCreatdate() {
		return getInt("creatdate");
	}

}
