package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrowditem<M extends BaseCrowditem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCrowdid(java.lang.Integer crowdid) {
		set("crowdid", crowdid);
		return (M)this;
	}
	
	public java.lang.Integer getCrowdid() {
		return getInt("crowdid");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setDesic(java.lang.String desic) {
		set("desic", desic);
		return (M)this;
	}
	
	public java.lang.String getDesic() {
		return getStr("desic");
	}

	public M setGoodid(java.lang.Integer goodid) {
		set("goodid", goodid);
		return (M)this;
	}
	
	public java.lang.Integer getGoodid() {
		return getInt("goodid");
	}

	public M setPrice(java.lang.Integer price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

}
