package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwUser<M extends BaseTfwUser<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setACCOUNT(java.lang.String ACCOUNT) {
		set("ACCOUNT", ACCOUNT);
		return (M)this;
	}
	
	public java.lang.String getACCOUNT() {
		return getStr("ACCOUNT");
	}

	public M setPASSWORD(java.lang.String PASSWORD) {
		set("PASSWORD", PASSWORD);
		return (M)this;
	}
	
	public java.lang.String getPASSWORD() {
		return getStr("PASSWORD");
	}

	public M setSALT(java.lang.String SALT) {
		set("SALT", SALT);
		return (M)this;
	}
	
	public java.lang.String getSALT() {
		return getStr("SALT");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	public M setBIRTHDAY(java.util.Date BIRTHDAY) {
		set("BIRTHDAY", BIRTHDAY);
		return (M)this;
	}
	
	public java.util.Date getBIRTHDAY() {
		return get("BIRTHDAY");
	}

	public M setSEX(java.lang.Integer SEX) {
		set("SEX", SEX);
		return (M)this;
	}
	
	public java.lang.Integer getSEX() {
		return getInt("SEX");
	}

	public M setEMAIL(java.lang.String EMAIL) {
		set("EMAIL", EMAIL);
		return (M)this;
	}
	
	public java.lang.String getEMAIL() {
		return getStr("EMAIL");
	}

	public M setPHONE(java.lang.String PHONE) {
		set("PHONE", PHONE);
		return (M)this;
	}
	
	public java.lang.String getPHONE() {
		return getStr("PHONE");
	}

	public M setROLEID(java.lang.String ROLEID) {
		set("ROLEID", ROLEID);
		return (M)this;
	}
	
	public java.lang.String getROLEID() {
		return getStr("ROLEID");
	}

	public M setDEPTID(java.lang.Integer DEPTID) {
		set("DEPTID", DEPTID);
		return (M)this;
	}
	
	public java.lang.Integer getDEPTID() {
		return getInt("DEPTID");
	}

	public M setSTATUS(java.lang.Integer STATUS) {
		set("STATUS", STATUS);
		return (M)this;
	}
	
	public java.lang.Integer getSTATUS() {
		return getInt("STATUS");
	}

	public M setCREATETIME(java.util.Date CREATETIME) {
		set("CREATETIME", CREATETIME);
		return (M)this;
	}
	
	public java.util.Date getCREATETIME() {
		return get("CREATETIME");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

}
