package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTfwDept<M extends BaseTfwDept<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public M setNUM(java.lang.Integer NUM) {
		set("NUM", NUM);
		return (M)this;
	}
	
	public java.lang.Integer getNUM() {
		return getInt("NUM");
	}

	public M setPID(java.lang.Integer PID) {
		set("PID", PID);
		return (M)this;
	}
	
	public java.lang.Integer getPID() {
		return getInt("PID");
	}

	public M setSIMPLENAME(java.lang.String SIMPLENAME) {
		set("SIMPLENAME", SIMPLENAME);
		return (M)this;
	}
	
	public java.lang.String getSIMPLENAME() {
		return getStr("SIMPLENAME");
	}

	public M setFULLNAME(java.lang.String FULLNAME) {
		set("FULLNAME", FULLNAME);
		return (M)this;
	}
	
	public java.lang.String getFULLNAME() {
		return getStr("FULLNAME");
	}

	public M setTIPS(java.lang.String TIPS) {
		set("TIPS", TIPS);
		return (M)this;
	}
	
	public java.lang.String getTIPS() {
		return getStr("TIPS");
	}

	public M setVERSION(java.lang.Integer VERSION) {
		set("VERSION", VERSION);
		return (M)this;
	}
	
	public java.lang.Integer getVERSION() {
		return getInt("VERSION");
	}

}
