package com.pc.cf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setNumber(java.lang.String number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.String getNumber() {
		return getStr("number");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setIscomplete(java.lang.Integer iscomplete) {
		set("iscomplete", iscomplete);
		return (M)this;
	}
	
	public java.lang.Integer getIscomplete() {
		return getInt("iscomplete");
	}

	public M setCompany(java.lang.Integer company) {
		set("company", company);
		return (M)this;
	}
	
	public java.lang.Integer getCompany() {
		return getInt("company");
	}

	public M setCreatdate(java.lang.Integer creatdate) {
		set("creatdate", creatdate);
		return (M)this;
	}
	
	public java.lang.Integer getCreatdate() {
		return getInt("creatdate");
	}

}
