package ikkong.platform.model;

import org.beetl.sql.core.annotatoin.Table;
import ikkong.core.annotation.BindID;
import ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-12-28 17:46:55
 */
@Table(name = "blog")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Blog extends BaseModel {
    	private Integer id;
    	private String content;
    	private String title;

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public String getContent() {
    		return content;
    	}

    	public void setContent(String content) {
    		this.content = content;
    	}

    	public String getTitle() {
    		return title;
    	}

    	public void setTitle(String title) {
    		this.title = title;
    	}

}
