package ikkong.platform.model;

import org.beetl.sql.core.annotatoin.Table;
import ikkong.core.annotation.BindID;
import ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-11-28 14:39:25
 */
@Table(name = "demand")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Demand extends BaseModel {
    	private Integer id;
    	private Integer billing; //是否需要开票
    	private Integer certification; //是否需要实名认证
    	private Integer companyid; //企业ID
    	private Integer creatdate;
    	private Integer deliverydate; //交付日期
    	private Integer demandtype1; //需求一级类型
    	private Integer demandtype2; //需求二级类型
    	private Integer endtime; //询价结束日期
    	private Integer freight; //运费承担方 供应方1 采购方2 其他0
    	private Integer invoice; //发票要求 无需发票0 增值税普通发票1 增值税专用发票2 个人发票3
    	private Integer mode; //交易方式 担保交易1 货到付款2 预付款3 其他0
    	private Integer payment;
    	private Integer quotedpriceid; //被选中的报价ID
    	private Integer rawmaterial; //原材料提供商 供应方1 采购方2 其他0
    	private Integer status; //需求状态0审核1招标中2签署合同3项目进行中4锁定暂停5已完结6已关闭
    	private Integer type; //草稿 还是预览
    	private String address;
    	private String cities;
    	private String contacts;
    	private String counties;
    	private String description; //详细描述
    	private String phone;
    	private String photo; //需求图片附件
    	private String provincial;
    	private String title; //询价主题

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getBilling() {
    		return billing;
    	}

    	public void setBilling(Integer billing) {
    		this.billing = billing;
    	}

    	public Integer getCertification() {
    		return certification;
    	}

    	public void setCertification(Integer certification) {
    		this.certification = certification;
    	}

    	public Integer getCompanyid() {
    		return companyid;
    	}

    	public void setCompanyid(Integer companyid) {
    		this.companyid = companyid;
    	}

    	public Integer getCreatdate() {
    		return creatdate;
    	}

    	public void setCreatdate(Integer creatdate) {
    		this.creatdate = creatdate;
    	}

    	public Integer getDeliverydate() {
    		return deliverydate;
    	}

    	public void setDeliverydate(Integer deliverydate) {
    		this.deliverydate = deliverydate;
    	}

    	public Integer getDemandtype1() {
    		return demandtype1;
    	}

    	public void setDemandtype1(Integer demandtype1) {
    		this.demandtype1 = demandtype1;
    	}

    	public Integer getDemandtype2() {
    		return demandtype2;
    	}

    	public void setDemandtype2(Integer demandtype2) {
    		this.demandtype2 = demandtype2;
    	}

    	public Integer getEndtime() {
    		return endtime;
    	}

    	public void setEndtime(Integer endtime) {
    		this.endtime = endtime;
    	}

    	public Integer getFreight() {
    		return freight;
    	}

    	public void setFreight(Integer freight) {
    		this.freight = freight;
    	}

    	public Integer getInvoice() {
    		return invoice;
    	}

    	public void setInvoice(Integer invoice) {
    		this.invoice = invoice;
    	}

    	public Integer getMode() {
    		return mode;
    	}

    	public void setMode(Integer mode) {
    		this.mode = mode;
    	}

    	public Integer getPayment() {
    		return payment;
    	}

    	public void setPayment(Integer payment) {
    		this.payment = payment;
    	}

    	public Integer getQuotedpriceid() {
    		return quotedpriceid;
    	}

    	public void setQuotedpriceid(Integer quotedpriceid) {
    		this.quotedpriceid = quotedpriceid;
    	}

    	public Integer getRawmaterial() {
    		return rawmaterial;
    	}

    	public void setRawmaterial(Integer rawmaterial) {
    		this.rawmaterial = rawmaterial;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getType() {
    		return type;
    	}

    	public void setType(Integer type) {
    		this.type = type;
    	}

    	public String getAddress() {
    		return address;
    	}

    	public void setAddress(String address) {
    		this.address = address;
    	}

    	public String getCities() {
    		return cities;
    	}

    	public void setCities(String cities) {
    		this.cities = cities;
    	}

    	public String getContacts() {
    		return contacts;
    	}

    	public void setContacts(String contacts) {
    		this.contacts = contacts;
    	}

    	public String getCounties() {
    		return counties;
    	}

    	public void setCounties(String counties) {
    		this.counties = counties;
    	}

    	public String getDescription() {
    		return description;
    	}

    	public void setDescription(String description) {
    		this.description = description;
    	}

    	public String getPhone() {
    		return phone;
    	}

    	public void setPhone(String phone) {
    		this.phone = phone;
    	}

    	public String getPhoto() {
    		return photo;
    	}

    	public void setPhoto(String photo) {
    		this.photo = photo;
    	}

    	public String getProvincial() {
    		return provincial;
    	}

    	public void setProvincial(String provincial) {
    		this.provincial = provincial;
    	}

    	public String getTitle() {
    		return title;
    	}

    	public void setTitle(String title) {
    		this.title = title;
    	}

}
