package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Authentication;

/**
 * Generated by Blade.
 * 2017-11-30 14:24:47
 */
public interface AuthenticationService extends IService<Authentication>{

}
