package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Blog;

/**
 * Generated by Blade.
 * 2017-12-28 17:46:55
 */
public interface BlogService extends IService<Blog>{

}
