package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.City;

/**
 * Generated by Blade.
 * 2017-11-28 14:39:25
 */
public interface CityService extends IService<City>{

}
