package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Company;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public interface CompanyService extends IService<Company>{

}
