package ikkong.platform.service;

import ikkong.core.base.service.IService;
import ikkong.platform.model.Demandtype;

/**
 * Generated by Blade.
 * 2017-12-05 01:01:32
 */
public interface DemandtypeService extends IService<Demandtype>{

}
